"""P2.2b Knowledge Projection Layer: Projects collection relations and notes into Obsidian Vault views."""

from .collection_indexer import CollectionIndexer, IndexResult, sanitize_url
from .contracts import (
    BoundaryViolationError,
    ClaimType,
    ClaimTypeInvalidError,
    CollectionMembership,
    CrossNoteSynthesisError,
    DigestClaim,
    DigestError,
    DigestRequest,
    EmptyEvidenceError,
    EmptySelectionError,
    EvidenceBundle,
    EvidenceExcerpt,
    EvidenceNoteNotInBundleError,
    EvidenceReference,
    HumanReviewState,
    InvalidNoteContentError,
    QuoteSpanMismatchError,
    SelectedNote,
    SelectionConfig,
    SelectionPositionMissingError,
    SourceConfig,
    SourceHashMismatchError,
    SpanOutOfBoundsError,
    SynthesizerConfig,
)
from .retriever import VaultRetriever

__all__ = [
    "CollectionIndexer",
    "IndexResult",
    "sanitize_url",
    "VaultRetriever",
    "DigestRequest",
    "SourceConfig",
    "SelectionConfig",
    "SynthesizerConfig",
    "SelectedNote",
    "CollectionMembership",
    "EvidenceBundle",
    "DigestClaim",
    "ClaimType",
    "HumanReviewState",
    "EvidenceExcerpt",
    "EvidenceReference",
    "DigestError",
    "BoundaryViolationError",
    "EmptySelectionError",
    "SelectionPositionMissingError",
    "InvalidNoteContentError",
    "EmptyEvidenceError",
    "EvidenceNoteNotInBundleError",
    "SourceHashMismatchError",
    "SpanOutOfBoundsError",
    "QuoteSpanMismatchError",
    "CrossNoteSynthesisError",
    "ClaimTypeInvalidError",
]
